spring:
  application:
    name: rag-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
    embedding:
      options:
        model: nomic-embed-text
      init:
        pull-model-strategy: when_missing
server:
  port: 8081
rag:
  pathPdf: "planeta_zorg.pdf"