spring:
  application:
    name: rag-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
server:
  port: 8081
rag:
  pdfName: "planeta_zorg.pdf"